#!/usr/bin/env python
# -*- coding: utf-8 -*-
import io
import os
import os.path as op
import sys

sys.path.append(op.join(op.dirname(op.abspath(__file__)), '..'))

from argparse import ArgumentParser

import pandas as pd
from lib import scatter

if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_argument('-i', '--input', default='')
    parser.add_argument('--figure_keys', nargs='+')
    parser.add_argument('--input_keys', nargs='+')
    parser.add_argument('-o', '--output', default='./')
    parser.add_argument('--separator', default='|')
    parser.add_argument('-d', '--display', action='store_true')
    parser.add_argument('--dpi', type=int, default=None)

    args = parser.parse_args()

    csv_f = io.StringIO(sys.stdin.read()) if args.input == '' else args.input
    in_df = pd.read_csv(csv_f, index_col=0)
    scatter(in_df, args.figure_keys, args.input_keys,
            output=args.output, sep=args.separator, dpi=args.dpi,
            display=args.display)
